version: "3.9"

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: lucky-vue-dev
    ports:
      - "${FRONTEND_PORT}:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    env_file:
      - ./frontend/.env
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: ["npm", "run", "dev","--", "--host", "0.0.0.0"]
    depends_on:
      - backend
    networks:
      - lucky-net

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: lucky-backend-dev
    ports:
      - "${BACKEND_PORT}:3000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    command: ["npm", "run", "start:dev"]
    depends_on:
      - db
    env_file:
      - ./backend/.env
    networks:
      - lucky-net

  db:
    image: postgres:13.2
    container_name: lucky_db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - lucky-net

networks:
  lucky-net:

volumes:
  db_data:
